name: Execução de Testes e Criação de Issues
run-name: Running - Execução de testes

on:
  workflow_call:

permissions:
  contents: write
  issues: write

jobs:
  generate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          repository: pj-integration-agent/automation
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
 
      - name: Instalação de dependências Node
        run: |
          npm install --save-dev @types/node
          npm install --save-dev @playwright/test typescript ts-node
 
      - name: Instalação do Playwright
        run: npx playwright install --with-deps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install groq pytest pytest-bdd

      - name: Execução de testes Playwright
        run: |
          npx playwright test 
        continue-on-error: true
 
      - name: Listar resultados dos testes
        run: ls -R test-results || echo "Nenhum arquivo encontrado"
 
      - name: Gerar análises com IA
        run: python ai/generate/generate_analise.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
 
      - name: Commit testes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin ${{ github.ref_name }}
          git add .
          git commit -m "🤖 Gerando Testes" || echo "Nada para commitar"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Criar issues com base na análise da IA
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const path = 'ai/analysis/analise_ia.txt';
            
            if (!fs.existsSync(path)) {
              core.info("Arquivo da IA não encontrado. Nenhuma issue será criada.");
              return;
            }
            
            const text = fs.readFileSync(path, 'utf8').trim();
            
            if (!text) {
              core.info("Arquivo da IA está vazio. Nenhuma issue será criada.");
              return;
            }
            
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            
            const title = `🧪 Relatório automático de falhas de testes (${new Date().toISOString().slice(0,10)})`;
            
            const body = `
            ## 🤖 Análise automática de testes (Playwright)
            
            ${text}
            
            ---
            _Gerado automaticamente pela pipeline CI_
            `;
            
            await github.rest.issues.create({
              owner,
              repo,
              title,
              body,
              labels: ["playwright", "test-failure", "ai-analysis"]
            });
